services:
  mongodb:
    image: mongo:latest
    container_name: admin-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: admin-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/admin_dashboard
      - JWT_SECRET=your_super_secret_key_here
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: admin-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
